/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

import javax.swing.*;
import java.awt.*;
import java.util.HashMap;
import java.util.Map;

/**
 *
 * @author elias.kretschmer
 */
public class settingsFormular extends javax.swing.JFrame {

    public Color background = Color.pink;
    public Color forground = Color.green;
    public int size = 20;

    private final Map<String,String> colors = new HashMap<>();



    /**
     * Creates new form settingsFormular
     */
    public settingsFormular() {
        initComponents();
        setColorHash();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jColorChooser1 = new javax.swing.JColorChooser();
        jLabel1 = new javax.swing.JLabel();
        closeButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        sizeTextField = new javax.swing.JTextField();
        applyButton = new javax.swing.JButton();
        forgroundColorDropDown = new javax.swing.JComboBox<>();
        backgroundTextField = new javax.swing.JTextField();
        backgroundColorDropDown = new javax.swing.JComboBox<>();
        forgroundTextField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Settings");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Settings");

        closeButton.setText("Close");
        closeButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeButtonMouseClicked(evt);
            }
        });

        jLabel2.setText("Size");

        jLabel3.setText("Background");

        jLabel4.setText("Forground");

        sizeTextField.setText("20");
        sizeTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                sizeTextFieldKeyReleased(evt);
            }
        });

        applyButton.setText("Apply");
        applyButton.setEnabled(false);
        applyButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                applyButtonMouseClicked(evt);
            }
        });

        forgroundColorDropDown.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Preset", "Magenta", "Pink", "Green", "Black", "Yellow", "Cyan", "Dark Gray", "Red", "Orange", "Gray", "White", "Blue", "Light Gray" }));
        forgroundColorDropDown.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                forgroundColorDropDownItemStateChanged(evt);
            }
        });

        backgroundTextField.setText("#ffafaf");
        backgroundTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                backgroundTextFieldKeyReleased(evt);
            }
        });

        backgroundColorDropDown.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Preset", "Magenta", "Pink", "Green", "Black", "Yellow", "Cyan", "Dark Gray", "Red", "Orange", "Gray", "White", "Blue", "Light Gray" }));
        backgroundColorDropDown.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                backgroundColorDropDownItemStateChanged(evt);
            }
        });
        backgroundColorDropDown.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backgroundColorDropDownActionPerformed(evt);
            }
        });

        forgroundTextField.setText("#00ff00");
        forgroundTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                forgroundTextFieldKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(applyButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(closeButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4))
                                .addGap(22, 22, 22)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(backgroundTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(backgroundColorDropDown, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(forgroundTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(forgroundColorDropDown, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(sizeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 156, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(sizeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(backgroundTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(backgroundColorDropDown, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(forgroundColorDropDown, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(forgroundTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 94, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(closeButton)
                    .addComponent(applyButton))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void closeButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeButtonMouseClicked
        if (applyButton.isEnabled()){
            int antwort = JOptionPane.showConfirmDialog(null, "Es gibt ungespeicherte Werte. Wollen sie wirklich beenden?", "Bestätigen",
                    JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
            if (antwort == JOptionPane.NO_OPTION){
                return;
            }
        }


        sizeTextField.setText(size + "");
        backgroundTextField.setText(colorToHex(background));
        forgroundTextField.setText(colorToHex(forground));
        setVisible(false);
        dispose();
    }//GEN-LAST:event_closeButtonMouseClicked

    private void applyButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_applyButtonMouseClicked
        if (!applyButton.isEnabled()){
           return;
        }
        size = Integer.parseInt(sizeTextField.getText());
        background = Color.decode(backgroundTextField.getText());
        forground = Color.decode(forgroundTextField.getText());
        reloadApply();

        System.out.println(size);
        System.out.println(background);
        System.out.println(forground);




    }//GEN-LAST:event_applyButtonMouseClicked

    private void sizeTextFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_sizeTextFieldKeyReleased
        reloadApply();
    }//GEN-LAST:event_sizeTextFieldKeyReleased

    private void backgroundTextFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_backgroundTextFieldKeyReleased
        reloadApply();
    }//GEN-LAST:event_backgroundTextFieldKeyReleased

    private void forgroundTextFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_forgroundTextFieldKeyReleased
        reloadApply();
    }//GEN-LAST:event_forgroundTextFieldKeyReleased

    private void backgroundColorDropDownItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_backgroundColorDropDownItemStateChanged
        String sel = evt.getItem().toString();
        backgroundTextField.setText(colors.get(sel));
        reloadApply();
    }//GEN-LAST:event_backgroundColorDropDownItemStateChanged

    private void forgroundColorDropDownItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_forgroundColorDropDownItemStateChanged
        String sel = evt.getItem().toString();
        forgroundTextField.setText(colors.get(sel));
        reloadApply();
    }//GEN-LAST:event_forgroundColorDropDownItemStateChanged

    private void backgroundColorDropDownActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backgroundColorDropDownActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_backgroundColorDropDownActionPerformed

    private void reloadApply(){
        try {
            int localSize = Integer.parseInt(sizeTextField.getText());
            Color localBackgroundColor = Color.decode(backgroundTextField.getText());
            Color localForgroundColor = Color.decode(forgroundTextField.getText());
            applyButton.setEnabled(localSize != size || !localBackgroundColor.equals(background) || !localForgroundColor.equals(forground));
        }catch (Exception e){
            applyButton.setEnabled(false);
        }
    }
    private String colorToHex(Color c){
        String hex = String.format("#%02X%02X%02X",
                c.getRed(),
                c.getGreen(),
                c.getBlue());

        return hex;
    }
    private void setColorHash(){
        colors.put("Preset", "");
        colors.put("Magenta", "#FF00FF");
        colors.put("Pink", "#FFAFAF");
        colors.put("Green", "#00FF00");
        colors.put("Black", "#000000");
        colors.put("Yellow", "#FFFF00");
        colors.put("Cyan", "#00FFFF");
        colors.put("Dark Gray", "#404040");
        colors.put("Red", "#FF0000");
        colors.put("Orange", "#FFC800");
        colors.put("Gray", "#808080");
        colors.put("White", "#FFFFFF");
        colors.put("Blue", "#0000FF");
        colors.put("Light Gray", "#C0C0C0");
    }

    
    /**
     * @param args the command line arguments
     */

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(settingsFormular.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(settingsFormular.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(settingsFormular.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(settingsFormular.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new settingsFormular().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton applyButton;
    private javax.swing.JComboBox<String> backgroundColorDropDown;
    private javax.swing.JTextField backgroundTextField;
    private javax.swing.JButton closeButton;
    private javax.swing.JComboBox<String> forgroundColorDropDown;
    private javax.swing.JTextField forgroundTextField;
    private javax.swing.JColorChooser jColorChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField sizeTextField;
    // End of variables declaration//GEN-END:variables
}
