
import java.awt.*;
import java.util.Random;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author michael
 */
public class zeichenFormular extends javax.swing.JFrame {
    
    int x;
    int y;
    Color c = Color.BLACK;
    Random rn = new Random();

    /**
     * Creates new form zeichenFormular
     */
    public zeichenFormular() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        endeButton = new javax.swing.JButton();
        clearButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        breiteField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        hoeheField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        setButton = new javax.swing.JButton();
        zeichenPanel1 = new zeichenPanel();
        startButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        endeButton.setText("Beenden");
        endeButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                endeButtonMouseClicked(evt);
            }
        });

        clearButton.setText("Clear");
        clearButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clearButtonMouseClicked(evt);
            }
        });

        jLabel2.setText("Größe:");

        jLabel3.setText("x");

        jLabel4.setText("Breite");

        jLabel5.setText("Höhe");

        setButton.setText("setzen");
        setButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                setButtonMouseClicked(evt);
            }
        });

        zeichenPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                zeichenPanel1MouseClicked(evt);
            }
        });

        startButton.setText("Start");
        startButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(breiteField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3))
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(hoeheField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(setButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(clearButton)
                        .addGap(18, 18, 18)
                        .addComponent(endeButton)))
                .addGap(18, 18, 18)
                .addComponent(startButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(zeichenPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(107, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(zeichenPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(breiteField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(hoeheField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(setButton)
                    .addComponent(endeButton)
                    .addComponent(clearButton)
                    .addComponent(startButton))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void endeButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_endeButtonMouseClicked
        int antwort = JOptionPane.showConfirmDialog(null, "Wollen Sie wirklich beenden?", "Bestätigen",
            JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if (antwort == JOptionPane.YES_OPTION)
        System.exit(0);
    }//GEN-LAST:event_endeButtonMouseClicked

    private void clearButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clearButtonMouseClicked
        // TODO add your handling code here:
        for (int i = 0; i < 20; i++) {
            for (int j = 0; j < 20; j++) {
                zeichenPanel1.setColor(i, j, Color.WHITE);
                zeichenPanel1.setNumber(i, j, 0);
                zeichenPanel1.setBombs(i, j, false);
            }
        }
    }//GEN-LAST:event_clearButtonMouseClicked

    private void setButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_setButtonMouseClicked
        // TODO add your handling code here:
        int b,h;

        b = Integer.parseInt(breiteField.getText());
        h = Integer.parseInt(hoeheField.getText());

        zeichenPanel1.setBreite(b);
        zeichenPanel1.setHoehe(h);
    }//GEN-LAST:event_setButtonMouseClicked

    private void zeichenPanel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_zeichenPanel1MouseClicked
        int x = evt.getX()/22;
        int y = evt.getY()/22;

        if (evt.getButton()==evt.BUTTON1){
            setColor(x,y,Color.RED);
            reloadNumbers();
        }
        
        if (evt.getButton()==evt.BUTTON3){
            setColor(x,y,Color.WHITE);
            reloadNumbers();
        }
    }//GEN-LAST:event_zeichenPanel1MouseClicked



    private void startButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startButtonActionPerformed
        clearButtonMouseClicked(null);
        generateBombs();
        reloadNumbers();
    }//GEN-LAST:event_startButtonActionPerformed

    private void reloadNumbers() {
        for (int i = 0; i < 20; i++) {
            for (int j = 0; j < 20; j++) {
                if (getBomb(i, j)) {
                    setNumber(i,j,0);
                    continue;
                }
                int count = 0;


                if (getBomb(i - 1, j - 1)) count++;
                if (getBomb(i, j - 1)) count++;
                if (getBomb(i + 1, j - 1)) count++;


                if (getBomb(i - 1, j)) count++;
                if (getBomb(i + 1, j)) count++;


                if (getBomb(i - 1, j + 1)) count++;
                if (getBomb(i, j + 1)) count++;
                if (getBomb(i + 1, j + 1)) count++;


                setNumber(i, j, count);
            }
        }
    }

    private void generateBombs(){
        for (int i = 0; i < 20; i++) {
            for (int j = 0; j < 20; j++) {
                if (rn.nextInt(3+1) == 0){ // 1zu3 chance
                    setBomb(i,j,true);
                    //setColor(i,j,Color.GREEN);
                }
            }
        }
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(zeichenFormular.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(zeichenFormular.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(zeichenFormular.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(zeichenFormular.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new zeichenFormular().setVisible(true);
            }
        });
    }





    //getter und setter ohne zeichenPanel1 jeweils
    public void setColor(int x, int y, Color c){
        zeichenPanel1.setColor(x, y, c);
    }
    public Color getColor(int x, int y){
        return zeichenPanel1.getColor(x, y);
    }

    public void setNumber(int x, int y, int number){
        zeichenPanel1.setNumber(x, y, number);
    }
    public void setBomb(int x, int y, boolean bol){
        zeichenPanel1.setBombs(x, y, bol);
    }
    public boolean getBomb(int x, int y){
        return zeichenPanel1.getBomb(x, y);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField breiteField;
    private javax.swing.JButton clearButton;
    private javax.swing.JButton endeButton;
    private javax.swing.JTextField hoeheField;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JButton setButton;
    private javax.swing.JButton startButton;
    private zeichenPanel zeichenPanel1;
    // End of variables declaration//GEN-END:variables
}
