
import java.awt.*;
import java.util.ArrayList;
import java.util.Random;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author michael
 */
public class zeichenFormular extends javax.swing.JFrame {
    Random rn = new Random();
    boolean gameStarted = false;

    /**
     * Creates new form zeichenFormular
     */
    public zeichenFormular() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        endeButton = new javax.swing.JButton();
        clearButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        breiteField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        hoeheField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        setButton = new javax.swing.JButton();
        zeichenPanel1 = new zeichenPanel();
        startButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        bombsCountLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        endeButton.setText("Beenden");
        endeButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                endeButtonMouseClicked(evt);
            }
        });


        clearButton.setText("Clear");
        clearButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clearButtonMouseClicked(evt);
            }
        });

        jLabel2.setText("Größe:");

        jLabel3.setText("x");

        jLabel4.setText("Breite");

        jLabel5.setText("Höhe");

        setButton.setText("setzen");
        setButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                setButtonMouseClicked(evt);
            }
        });

        zeichenPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                zeichenPanel1MouseClicked(evt);
            }
        });

        startButton.setText("Start");

        startButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startButtonActionPerformed(evt);
            }
        });

        jLabel1.setText("Bombs: ");

        bombsCountLabel.setText("0");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(breiteField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3))
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(hoeheField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(setButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(clearButton)
                        .addGap(18, 18, 18)
                        .addComponent(endeButton)))
                .addGap(18, 18, 18)
                .addComponent(startButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(zeichenPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bombsCountLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(zeichenPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(bombsCountLabel)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(breiteField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(hoeheField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(setButton)
                    .addComponent(endeButton)
                    .addComponent(clearButton)
                    .addComponent(startButton))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void endeButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_endeButtonMouseClicked
        int antwort = JOptionPane.showConfirmDialog(null, "Wollen Sie wirklich beenden?", "Bestätigen",
            JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if (antwort == JOptionPane.YES_OPTION)
        System.exit(0);
    }//GEN-LAST:event_endeButtonMouseClicked

    private void clearButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clearButtonMouseClicked
        // TODO add your handling code here:
        gameStarted = false;
        for (int i = 0; i < 20; i++) {
            for (int j = 0; j < 20; j++) {
                setFieldColor(i, j, Color.GREEN);
                setNumber(i, j, 0);
                setBomb(i, j, false);
                setExplored(i, j, false);
                setNumberColor(i,j,Color.GREEN);
                setFlag(i,j,false);

                bombsCountLabel.setText("0");
            }
        }
    }//GEN-LAST:event_clearButtonMouseClicked

    private void setButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_setButtonMouseClicked
        // TODO add your handling code here:
        int b,h;

        b = Integer.parseInt(breiteField.getText());
        h = Integer.parseInt(hoeheField.getText());

        zeichenPanel1.setBreite(b);
        zeichenPanel1.setHoehe(h);
    }//GEN-LAST:event_setButtonMouseClicked

    private void zeichenPanel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_zeichenPanel1MouseClicked
        int x = evt.getX()/22;
        int y = evt.getY()/22;

        if (evt.getButton()==evt.BUTTON1){
            if (!gameStarted) {
                clearButtonMouseClicked(null);
                generateBombs(x, y);
                reloadNumbers();
                generateFreeSpaces(x,y,Color.pink);
                gameStarted = true;
            }else{
                if (getFlag(x,y) && getExplored(x,y)){
                    return;
                }
                if (getBomb(x,y)){
                    System.out.println("Booooooooooooooooooooooooooooooooooooooooooom");
                }else{
                    setExplored(x,y,true);
                    setFieldColor(x,y,Color.PINK);
                    setNumberColor(x,y,Color.BLACK);
                    generateFreeSpaces(x,y,Color.PINK);
                }
            }
        }

        if (evt.getButton()==evt.BUTTON2){
            System.out.println("------------------------------------");
            System.out.println("X: " + x + " Y: " + y);
            System.out.println("Bomb: " + getBomb(x,y));
            System.out.println("Explored: " + getExplored(x,y));
            System.out.println("Flag: " + getFlag(x,y));
            System.out.println("Color: " + rgbToAnsi(getColor(x,y)) + "■" + "\033[0m");
            System.out.println("Number: " + getNumber(x,y));
            System.out.println("NumberColor: " + rgbToAnsi(getNumberColor(x,y)) + "■" + "\033[0m");
        }
        
        if (evt.getButton()==evt.BUTTON3){ //Rechtsklick
            if (!getExplored(x,y)){ //place flag
                if (getFlag(x,y)){
                    setCombinedColor(x,y,Color.GREEN);
                    setFlag(x,y,false);
                }else {
                    setCombinedColor(x, y, Color.RED);
                    setFlag(x,y,true);
                }
            }
            reloadNumbers();
        }
    }//GEN-LAST:event_zeichenPanel1MouseClicked



    private void startButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startButtonActionPerformed
    }//GEN-LAST:event_startButtonActionPerformed

    private void reloadNumbers() {
        int sizeX = zeichenPanel1.getBreite();
        int sizeY = zeichenPanel1.getHoehe();
        for (int i = 0; i < sizeX; i++) {
            for (int j = 0; j < sizeY; j++) {
                if (getBomb(i, j)) {
                    setNumber(i,j,0);
                    continue;
                }
                int count = 0;

                for (int k = i-1; k < i+2; k++) {
                    for (int l = j-1; l < j+2; l++) {
                        if (getBomb(k, l)) count++;
                    }
                }
                setNumber(i, j, count);
            }
        }
    }

    private void generateFreeSpaces(int x, int y, Color c){
        if (x<0 || x>19||y<0 || y>19){
            return;
        }
        if (getNumber(x,y) != 0){
            setExplored(x,y,true);
            setFieldColor(x,y, c);
            setNumberColor(x,y,Color.BLACK);
            return;
        }
        setFieldColor(x, y, c);
        setExplored(x,y,true);
        setNumberColor(x,y,Color.BLACK);

        int[][] neighbors = {{x, y + 1}, {x - 1, y}, {x + 1, y}, {x, y - 1}};
        for (int[] pos : neighbors) {
            if (!getBomb(pos[0], pos[1]) && !getExplored(pos[0], pos[1])) {
                generateFreeSpaces(pos[0], pos[1],c);
            }
        }

    }

    private void generateBombs(int startX, int startY){
        int sizeX = zeichenPanel1.getBreite();
        int sizeY = zeichenPanel1.getHoehe();
        ArrayList<Integer> spawnX = new ArrayList<>();
        ArrayList<Integer> spawnY = new ArrayList<>();


        for (int i = 0; i < sizeX; i++) {
            for (int j = 0; j < sizeY; j++) {

                if (i == startX && j == startY){
                    for (int k = i-1; k < i+2; k++) {
                        for (int l = j-1; l < j+2; l++) {
                            setBomb(k,l,false);
                            //setColor(k,l,Color.GREEN);
                            spawnX.add(k);
                            spawnY.add(l);
                        }
                    }
                }

                if (spawnX.contains(i) && spawnY.contains(j)){
                    //setColor(i,j,Color.GREEN);
                    break;
                }

                int bombsPlaced = Integer.parseInt(bombsCountLabel.getText());
                int remainingBombs = 100 - bombsPlaced;
                int remainingFields = sizeX*sizeY - (i*sizeY + j);

                if (rn.nextDouble() < (double)remainingBombs / remainingFields) {
                    setBomb(i,j,true);
                    //setColor(i,j,Color.RED);
                    bombsCountLabel.setText(bombsPlaced + 1 + "");
                }

            }
        }
//        for(int i: spawn.keySet()){
//            for(int j: spawn.values()){
//                System.out.println("X: " + i + " Y: " + j);
//            }
//
//        }
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(zeichenFormular.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(zeichenFormular.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(zeichenFormular.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(zeichenFormular.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new zeichenFormular().setVisible(true);
            }
        });
    }





    //getter und setter ohne zeichenPanel1 jeweils
    public void setFieldColor(int x, int y, Color c){
        zeichenPanel1.setFieldColor(x, y, c);
    }
    public Color getColor(int x, int y){
        return zeichenPanel1.getFieldColor(x, y);
    }

    public void setNumber(int x, int y, int number){
        zeichenPanel1.setNumber(x, y, number);
    }
    public int getNumber(int x, int y){
        return zeichenPanel1.getNumber(x,y);
    }

    public void setBomb(int x, int y, boolean bol){
        zeichenPanel1.setBombs(x, y, bol);
    }
    public boolean getBomb(int x, int y){
        return zeichenPanel1.getBomb(x, y);
    }

    public void setExplored(int x, int y, boolean bol){
        zeichenPanel1.setExplored(x, y, bol);
    }
    public boolean getExplored(int x, int y){
        return zeichenPanel1.getExplored(x, y);
    }

    public void setNumberColor(int x, int y, Color c){
        zeichenPanel1.setNumberColor(x, y, c);
    }
    public Color getNumberColor(int x, int y){
        return zeichenPanel1.getNumberColor(x, y);
    }
    public void setCombinedColor(int x, int y, Color c){
        setNumberColor(x,y,c);
        setFieldColor(x,y,c);
    }

    public void setFlag(int x, int y, boolean bol){
        zeichenPanel1.setFlag(x, y, bol);
    }
    public boolean getFlag(int x, int y){
        return zeichenPanel1.getFlag(x, y);
    }



    public String rgbToAnsi(Color color){
        return "\033[38;2;" + color.getRed() + ";" + color.getGreen() + ";" + color.getBlue() + "m";
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bombsCountLabel;
    private javax.swing.JTextField breiteField;
    private javax.swing.JButton clearButton;
    private javax.swing.JButton endeButton;
    private javax.swing.JTextField hoeheField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JButton setButton;
    private javax.swing.JButton startButton;
    private zeichenPanel zeichenPanel1;
    // End of variables declaration//GEN-END:variables
}
