
import java.awt.*;
import java.util.ArrayList;
import java.util.Collections;
import java.util.HashMap;
import java.util.Random;
import javax.swing.*;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author michael
 */
public class zeichenFormular extends javax.swing.JFrame {
    public static zeichenFormular zF = new zeichenFormular();

    Random rn = new Random();
    boolean gameStarted = false;
    boolean gameLost = false;
    boolean gameWon = false;

    boolean iterative = false;  //das ändern um zwischen iterative und recursive zu wechseln (nicht in settingsmenu)

    public Color background = Color.pink;
    public Color forground = Color.green;
    public int size = 20; // not in use
    private final int bombCount = 100;


    private settingsFormular settingsFormular;



    /**
     * Creates new form zeichenFormular
     */
    public zeichenFormular() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        resetButton = new javax.swing.JButton();
        zeichenPanel1 = new zeichenPanel();
        jLabel1 = new javax.swing.JLabel();
        bombsCountLabel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        flagCountLabel = new javax.swing.JLabel();
        progressLabel = new javax.swing.JLabel();
        loseLabel = new javax.swing.JLabel();
        revealButton = new javax.swing.JButton();
        settingsButton = new javax.swing.JButton();
        winLable = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        resetButton.setText("Reset");
        resetButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                resetButtonMouseClicked(evt);
            }
        });

        zeichenPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                zeichenPanel1MouseClicked(evt);
            }
        });

        jLabel1.setText("Bombs: ");

        bombsCountLabel.setText("0");

        jLabel2.setText("Flags:");

        jLabel3.setText("Progress:");

        flagCountLabel.setText("0");

        progressLabel.setText("0/0");

        loseLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        loseLabel.setForeground(new java.awt.Color(255, 51, 51));
        loseLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        loseLabel.setText("Du bist explodiert. Drücke \"Reset\" um ein neues Spiel zu starten oder \"Reveal\" um die übrigen Bomben zu sehen.");
        loseLabel.setAutoscrolls(true);

        revealButton.setText("Reveal");
        revealButton.setEnabled(false);
        revealButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                revealButtonMouseClicked(evt);
            }
        });

        settingsButton.setText("Settings");
        settingsButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                settingsButtonMouseClicked(evt);
            }
        });

        winLable.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        winLable.setForeground(new java.awt.Color(0, 153, 0));
        winLable.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        winLable.setText("Du hast Gewonnen. Alle Bomben wurden in diesem Bereich geräumt. Das FBI ist stolz auf dich");
        winLable.setAutoscrolls(true);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(loseLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addComponent(zeichenPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 441, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(flagCountLabel))
                                    .addComponent(jLabel3)
                                    .addComponent(progressLabel)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(bombsCountLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(156, 156, 156)
                                .addComponent(settingsButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(resetButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(revealButton)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(winLable, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(zeichenPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(bombsCountLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(flagCountLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(progressLabel)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(resetButton)
                    .addComponent(revealButton)
                    .addComponent(settingsButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(loseLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(3, 3, 3)
                .addComponent(winLable, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        loseLabel.setVisible(false);
        winLable.setVisible(false);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void resetButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_resetButtonMouseClicked
        gameStarted = false;
        gameLost = false;
        gameWon = false;
        for (int i = 0; i < 20; i++) {
            for (int j = 0; j < 20; j++) {
                setFieldColor(i, j, forground);
                setNumber(i, j, 0);
                setBomb(i, j, false);
                setExplored(i, j, false);
                setNumberColor(i,j,forground);
                setFlag(i,j,false);
                setIcon(i,j,"", Color.BLACK);
            }
        }
        flagCountLabel.setText("0");
        bombsCountLabel.setText("0");
        progressLabel.setText("0/0");
        loseLabel.setVisible(false);
        winLable.setVisible(false);
        revealButton.setEnabled(false);

    }//GEN-LAST:event_resetButtonMouseClicked

    private void zeichenPanel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_zeichenPanel1MouseClicked
        int x = evt.getX()/22;
        int y = evt.getY()/22;
        if (evt.getButton()==evt.BUTTON1){
            if (gameLost || gameWon){
                return;
            }

            if (!gameStarted) {
                resetButtonMouseClicked(null);
                generateBombs(x, y);
                reloadNumbers();

                if (iterative)generateFreeSpacesIterative(x,y,background);
                else generateFreeSpaces(x,y,background);

                reloadProgress();
                gameStarted = true;



            }else{
                if (getFlag(x,y) || getExplored(x,y)){
                    return;
                }
                if (getBomb(x,y)){
                    loseLabel.setVisible(true);
                    revealButton.setEnabled(true);
                    gameLost = true;
                    progressLabel.setText("Lost");
                    setIcon(x,y,"💣", Color.RED);
                    setFieldColor(x,y,Color.BLACK);




                }else{
                    setExplored(x,y,true);
                    setFieldColor(x,y,background);
                    setNumberColor(x,y,Color.BLACK);
                    if (iterative)generateFreeSpacesIterative(x,y,background);
                    else generateFreeSpaces(x,y,background);
                    reloadProgress();

                }
            }
            if (progressLabel.getText().equals((400-bombCount) + "/" + (400-bombCount)) && Integer.parseInt(flagCountLabel.getText()) == bombCount){
                winLable.setVisible(true);
                gameWon = true;
            }

        }

        if (evt.getButton()==evt.BUTTON2){
            System.out.println("------------------------------------");
            System.out.println("X: " + x + " Y: " + y);
            System.out.println("Bomb: " + getBomb(x,y));
            System.out.println("Explored: " + getExplored(x,y));
            System.out.println("Flag: " + getFlag(x,y));
            System.out.println("Color: " + rgbToAnsi(getColor(x,y)) + "■" + "\033[0m");
            System.out.println("Number: " + getNumber(x,y));
            System.out.println("NumberColor: " + rgbToAnsi(getNumberColor(x,y)) + "■" + "\033[0m");
            System.out.println("Icon: " + getIcon(x,y));
            System.out.println("IconColor: " + rgbToAnsi(getIconColor(x,y)) + "■" + "\033[0m");

            int c = 0;
            for (int i = 0; i < 20; i++) {
                for (int j = 0; j < 20; j++) {
                    if (getBomb(i,j)){
                      c++;
                    }
                }
            }
            System.out.println("Bomben: " + c);

        }
        
        if (evt.getButton()==evt.BUTTON3){ //Rechtsklick
            if (gameLost){
                return;
            }
            if (!getExplored(x,y)){ //place flag
                if (getFlag(x,y)){
                    //setCombinedColor(x,y,Color.GREEN);
                    setFlag(x,y,false);
                    setIcon(x, y, "",  Color.BLACK);
                    flagCountLabel.setText(Integer.parseInt(flagCountLabel.getText()) - 1 + "");
                }else {
                    //setCombinedColor(x, y, Color.RED);
                    setFlag(x,y,true);
                    setIcon(x,y, "🚩",Color.RED);
                    flagCountLabel.setText(Integer.parseInt(flagCountLabel.getText()) + 1 + "");
                }
            }
            reloadNumbers();
            if (progressLabel.getText().equals((400-bombCount) + "/" + (400-bombCount)) && Integer.parseInt(flagCountLabel.getText()) == bombCount){
                winLable.setVisible(true);
                gameWon = true;
            }
        }
    }//GEN-LAST:event_zeichenPanel1MouseClicked

    private void revealButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_revealButtonMouseClicked
        if (!revealButton.isEnabled()){
            return;
        }

        for (int x = 0; x < 20; x++) {
            for (int y = 0; y < 20; y++) {
                if (getBomb(x,y)){
                    if (getFlag(x,y)){
                        setFieldColor(x,y,Color.GREEN);
                    }else {
                        setFieldColor(x,y,Color.RED);
                    }
                    setIcon(x,y,"💣", Color.BLACK);
                    continue;
                }
                if (iterative)generateFreeSpacesIterative(x,y,background);
                else generateFreeSpaces(x,y,background);
            }
        }
    }//GEN-LAST:event_revealButtonMouseClicked

    private void settingsButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_settingsButtonMouseClicked
        settingsFormular = new settingsFormular(zF);
        settingsFormular.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        settingsFormular.setVisible(true);
    }//GEN-LAST:event_settingsButtonMouseClicked

    private void reloadNumbers() {


        int sizeX = zeichenPanel1.getBreite();
        int sizeY = zeichenPanel1.getHoehe();
        for (int i = 0; i < sizeX; i++) {
            for (int j = 0; j < sizeY; j++) {
                if (getBomb(i, j)) {
                    setNumber(i,j,0);
                    continue;
                }
                int count = 0;

                for (int k = i-1; k < i+2; k++) {
                    for (int l = j-1; l < j+2; l++) {
                        if (getBomb(k, l)) count++;
                    }
                }
                setNumber(i, j, count);
            }
        }
    }

    private void generateFreeSpaces(int x, int y, Color c){
        if (x<0 || x>19||y<0 || y>19){
            return;
        }
        if (getNumber(x,y) != 0){
            setExplored(x,y,true);
            setFieldColor(x,y, c);
            setNumberColor(x,y,getIntColor(getNumber(x,y)));
            return;
        }
        setFieldColor(x, y, c);
        setExplored(x,y,true);
        setNumberColor(x,y,getIntColor(getNumber(x,y)));

        for (int i = x-1; i < x+2; i++) {
            for (int j = y-1; j < y+2; j++) {
                if (!getBomb(i,j) && !getExplored(i,j)) {
                    generateFreeSpaces(i,j,c);
                }
            }
        }

    }

    private void generateFreeSpacesIterative(int x, int y, Color c) {
        ArrayList<Point> list = new ArrayList<>();

        setExplored(x, y, true);
        list.add(new Point(x, y));

        while (!list.isEmpty()) {

            Point p = list.remove(0);
            x = p.x;
            y = p.y;

            setFieldColor(x, y, c);
            setNumberColor(x, y, getIntColor(getNumber(x, y)));

            if (getNumber(x, y) != 0) continue;

            for (int i = x - 1; i <= x + 1; i++) {
                for (int j = y - 1; j <= y + 1; j++) {

                    if (i < 0 || i > 19 || j < 0 || j > 19) continue;
                    if (getBomb(i, j) || getExplored(i, j)) continue;

                    setExplored(i, j, true);
                    list.add(new Point(i, j));
                }
            }
        }

    }

    private void generateBombs(int startX, int startY) {
        int sizeX = zeichenPanel1.getBreite();
        int sizeY = zeichenPanel1.getHoehe();

        ArrayList<Point> possibleFields = new ArrayList<>();

        // Alle erlaubten Felder sammeln
        for (int i = 0; i < sizeX; i++) {
            for (int j = 0; j < sizeY; j++) {

                boolean blocked =
                        i >= startX - 1 && i <= startX + 1 &&
                                j >= startY - 1 && j <= startY + 1;

                if (!blocked) {
                    possibleFields.add(new Point(i, j));
                } else {
                    setBomb(i, j, false);
                }
            }
        }

        // Liste mischen
        Collections.shuffle(possibleFields, rn);

        // Nicht mehr Bomben setzen als Felder da sind
        int bombsToPlace = Math.min(bombCount, possibleFields.size());

        for (int n = 0; n < bombsToPlace; n++) {
            Point p = possibleFields.get(n);
            setBomb(p.x, p.y, true);
        }

        bombsCountLabel.setText(String.valueOf(bombsToPlace));
    }

    private void reloadProgress(){
        int total = zeichenPanel1.getBreite() * zeichenPanel1.getHoehe() - Integer.parseInt(bombsCountLabel.getText());
        int explored = 0;
        for (int i = 0; i < 20; i++){
            for (int j = 0; j < 20; j++){
                if (getExplored(i,j)){
                explored++;
                }
            }
        }

        progressLabel.setText(explored + "/" + total);
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(zeichenFormular.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(zeichenFormular.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(zeichenFormular.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(zeichenFormular.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                zF.setVisible(true);
                zF.setTitle("MineSweeper");
                zF.setSize(650, 590);
            }
        });
    }

    public void applySettings(Color bg, Color fg, int newSize) {
        this.background = bg;
        this.forground = fg;
        this.size = newSize;

        for (int x = 0; x < 20; x++) {
            for (int y = 0; y < 20; y++) {
                if (!getExplored(x, y)) {
                    setFieldColor(x, y, forground);
                    setNumberColor(x, y, forground);
                } else {
                    setFieldColor(x, y, background);
                    setNumberColor(x, y, getIntColor(getNumber(x, y)));
                }
            }
        }
        zeichenPanel1.repaint();
    }



    //getter und setter ohne zeichenPanel1 jeweils
    public void setFieldColor(int x, int y, Color c){
        zeichenPanel1.setFieldColor(x, y, c);
    }
    public Color getColor(int x, int y){
        return zeichenPanel1.getFieldColor(x, y);
    }

    public void setNumber(int x, int y, int number){
        zeichenPanel1.setNumber(x, y, number);
    }
    public int getNumber(int x, int y){
        return zeichenPanel1.getNumber(x,y);
    }

    public void setBomb(int x, int y, boolean bol){
        zeichenPanel1.setBombs(x, y, bol);
    }
    public boolean getBomb(int x, int y){
        return zeichenPanel1.getBomb(x, y);
    }

    public void setExplored(int x, int y, boolean bol){
        zeichenPanel1.setExplored(x, y, bol);
    }
    public boolean getExplored(int x, int y){
        return zeichenPanel1.getExplored(x, y);
    }

    public void setNumberColor(int x, int y, Color c){
        zeichenPanel1.setNumberColor(x, y, c);
    }
    public Color getNumberColor(int x, int y){
        return zeichenPanel1.getNumberColor(x, y);
    }

    public void setCombinedColor(int x, int y, Color c){
        setNumberColor(x,y,c);
        setFieldColor(x,y,c);
    }

    public void setFlag(int x, int y, boolean bol){
        zeichenPanel1.setFlag(x, y, bol);
    }
    public boolean getFlag(int x, int y){
        return zeichenPanel1.getFlag(x, y);
    }

    public void setIcon(int x, int y, String str, Color c){
        zeichenPanel1.setIcon(x,y,str);
        zeichenPanel1.setIconColor(x,y,c);
    }
    public String getIcon(int x, int y){
        return zeichenPanel1.getIcon(x,y);
    }

    public Color getIconColor(int x, int y){
        return zeichenPanel1.getIconColor(x, y);
    }


    public String rgbToAnsi(Color color){
        return "\033[38;2;" + color.getRed() + ";" + color.getGreen() + ";" + color.getBlue() + "m";
    }

    private Color getIntColor(int number){
        switch (number){
            case 1 -> {
                return (new Color(0, 0, 255));
            }
            case 2 -> {
                return new Color(0, 128,0);
            }
            case 3 -> {
                return new Color(255,0,0);
            }
            case 4 -> {
                return new Color(0,0,128);
            }
            case 5 -> {
                return new Color(128,0,0);
            }
            case 6 -> {
                return new Color(0,128,128);
            }
            case 7 -> {
                return new Color(0,0,0);
            }
            case 8 -> {
                return new Color(128,128,128);
            }
            default -> {
                return Color.WHITE;
            }
        }

    }




    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bombsCountLabel;
    private javax.swing.JLabel flagCountLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel loseLabel;
    private javax.swing.JLabel progressLabel;
    private javax.swing.JButton resetButton;
    private javax.swing.JButton revealButton;
    private javax.swing.JButton settingsButton;
    private javax.swing.JLabel winLable;
    private zeichenPanel zeichenPanel1;
    // End of variables declaration//GEN-END:variables
}
